#!/bin/bash

echo "🚀 Probando el sistema de chat GreenLoop"

echo "📝 Pasos para probar la funcionalidad:"

echo ""
echo "1. BACKEND:"
echo "   - Ejecuta: cd /Users/marcosotomaceda/Desktop/proyecto-backend-greenloopppp_front_initial"
echo "   - Ejecuta: ./mvnw spring-boot:run"
echo "   - El backend estará disponible en: http://localhost:8081"

echo ""
echo "2. FRONTEND:"
echo "   - Ejecuta: cd /Users/marcosotomaceda/Desktop/proyecto-backend-greenloopppp_front_initial/vite-template-greenloop"
echo "   - Ejecuta: npm run dev"
echo "   - El frontend estará disponible en: http://localhost:5173"

echo ""
echo "3. PRUEBAS:"
echo "   a) Inicia sesión con dos usuarios diferentes en dos navegadores"
echo "   b) Ve a un producto de otro usuario"
echo "   c) Haz clic en 'Contactar propietario'"
echo "   d) Deberías ser redirigido al chat"
echo "   e) Envía un mensaje y verifica que llegue en tiempo real"

echo ""
echo "4. ENDPOINTS DE CHAT DISPONIBLES:"
echo "   - POST /api/chats/start?otherUserId={id}&productId={id}"
echo "   - GET /api/chats/my-chats"
echo "   - GET /api/chats/{chatId}/messages"
echo "   - WebSocket: ws://localhost:8081/ws"

echo ""
echo "5. FUNCIONALIDADES IMPLEMENTADAS:"
echo "   ✅ Autenticación WebSocket con JWT"
echo "   ✅ Inicio de chat desde producto"
echo "   ✅ Mensajes en tiempo real"
echo "   ✅ Lista de chats del usuario"
echo "   ✅ Historial de mensajes"
echo "   ✅ Indicador de escritura"
echo "   ✅ Manejo de errores"

echo ""
echo "🔧 CAMBIOS REALIZADOS:"
echo ""
echo "BACKEND:"
echo "   - ✅ Mejorado ChatService.startChat() para buscar chats en ambas direcciones"
echo "   - ✅ Creado AuthChannelInterceptor para autenticación WebSocket"
echo "   - ✅ Actualizado WebSocketConfig con interceptor de autenticación"
echo ""
echo "FRONTEND:"
echo "   - ✅ Agregado botón 'Contactar propietario' funcional"
echo "   - ✅ Mejorado chatService con manejo de errores"
echo "   - ✅ Creado WebSocketContext para manejo centralizado"
echo "   - ✅ Integración completa con navegación al chat"

echo ""
echo "🐛 DEBUGGING:"
echo "   - Verifica que el token JWT esté en localStorage"
echo "   - Revisa la consola del navegador para errores WebSocket"
echo "   - Verifica que los usuarios sean diferentes"
echo "   - Comprueba que el producto no pertenezca al usuario actual"

echo ""
echo "✨ ¡El sistema de chat está listo para usar!"
